### ISSUE TITLE
Непечатные символы в txt файлах

### ISSUE THREAD

**Issue by vasek00786** [amokb/medos#126]
Необходимо составить и использовать таблицу замен для непечатных символов для матричных принтеров. 
Пример:  " – " " - "

**Comment by Milamesher** [comment]
жду список поддерживаемых принтером символов

**Comment by vasek00786** [comment]
[CP 866.xlsx](https://github.com/amokb/medos/files/3200849/CP.866.xlsx)
Табличка подоспела
