### ISSUE TITLE
Отчет по тяжелым больным

### ISSUE THREAD

**Issue by Rashgild** [amokb/medos#15]
После выполнения задачи #16 . Сделать отчет-сводную форму по тяжелым больным под наблюдением.

--требуется уточнение по задаче

**Comment by Milamesher** [comment]
На данный момент (после уточнения у автора заявки) сделан отчёт по больным под наблюдением:  (по отделениям/по всем отделениям, дата обязательна). Необходимо показать автору заявки.

**Comment by Milamesher** [comment]
После уточнения у автора заявки необходимо переделать отчёт (нужна таблица: список отделений и кол-во под наблюдением, строка - ссылка, переходим на конкретных пациентов текущего отделения), таблица строится на определённую дату (в ночь).

**Comment by Milamesher** [comment]
Правки внесены. Жду, пока не придёт автор заявки.
