### ISSUE TITLE
Отметка о наблюдении лечащим врачом 

### ISSUE THREAD

**Issue by Rashgild** [amokb/medos#16]
Дать возможность отмечать врачам тяжелых больных под наблюдением. После чего #15 

--требуется уточнение по задаче

**Comment by Milamesher** [comment]
Нужно предусмотреть внесение фамилий пациентов под наблюдением в отдельную ячейку отделения вручную ежедневно до сдачи смены.

**Comment by Milamesher** [comment]
На данный момент сделано: 2 новых сущности без формы (сам список с датой и список пациентов для каждого списка), добавление пациентов в список, удаление (соотв. постановка и снятие наблюдения), список автоматически добавляется по дате при добавлении первого пациента. Необходимо показать автору заявки.

**Comment by Milamesher** [comment]
После уточнения у автора заявки необходимо доделать отчёт по больным, потом закрою и эту задачу.
