### ISSUE TITLE
ФСС. Журнал отправки.

### ISSUE THREAD

**Issue by Rashgild** [amokb/medos#21]
-Возможность просмотреть отправленные ЭЛН;
-При(до) отправке листа отображать его статус.

**Comment by vasek00786** [comment]
Сделать журнал отправки случая нетрудоспособности в ФСС. Отображать историю отправки с результатом. Возможно, в случае успешной отправки помечать случай (к примеру, зеленым цветом) как отправленный.

**Comment by vasek00786** [comment]
Выделение цветом под вопросом, журнал сделан, статус экспорта отображается.
