### ISSUE TITLE
Добавить возможность прокрутки колесом мыши выпадающего списка

### ISSUE THREAD

**Issue by vasek00786** [amokb/medos#29]

**Comment by Milamesher** [comment]
На данный момент сделана прокрутка колесом мыши, добавлены кнопки прокрутки для autocomplete и otma. Проверено на старом firefox, на двух терминалках. На одной (с той же версией браузера) работало некорректно, пока не коммичу. Возможно, будет терминалка для теста.

**Comment by Milamesher** [comment]
Нужно при enter - переходить к следующему без вывода списка и получения первого значения

**Comment by Milamesher** [comment]
Прокрутка, кнопки, фокус с jsp, переход по enter - работают.
