### ISSUE TITLE
В журнал обращений добавить случаи отказов по экстренным пунктам

### ISSUE THREAD

**Issue by vasek00786** [amokb/medos#46]
Прошу ввести в приемное отделегние в журнал обращений случаи отказов (отсутствие показаний к госпитализации, переводы в другие ЛПУ, самовольно покинул отделение) по экстренным пунктам ЛОР, ЧЛХ, МХГ.
П.С, ХЗ что это такое

**Comment by Milamesher** [comment]
Неактуальная задача.
