### ISSUE TITLE
ЭЛН

### ISSUE THREAD

**Issue by Rashgild** [amokb/medos#56]
Подписывать ЭЛН от лица заведующего отделения.

**Comment by Rashgild** [comment]
Импортировать ЛН, если есть след.номер, создавать ЛН

**Comment by Rashgild** [comment]
Экспорт ЭЛН - запрет редактирования после выгрузки

**Comment by Rashgild** [comment]
2 @Rashgild , проверки с placementservice & earlypregnancyregistration

**Comment by Milamesher** [comment]
почти 3 месяца с последнего коммита. Задачу закрываю
