### ISSUE TITLE
Критерии качества помощи

### ISSUE THREAD

**Issue by vasek00786** [amokb/medos#63]
Реализовать: при выписке пациента с диагнозом, входящим в определенный перечень, выводить окно с перечнем критериев, на которые необходимо ответить. Без заполнения этих данных - выписка пациента невозможна.

**Comment by Milamesher** [comment]
Выполнено, надо показать руководству.

**Comment by Milamesher** [comment]
Необходимо выводить подсказку о критериях при создании основного клинического диагноза. Необходимо показывать, что выполнено (при подсчёте автоматически) в ЭК зав. Нужно убрать код критерия

**Comment by Milamesher** [comment]
Необходимо выводить поле для сохранения примечания при смене значения да-нет последующим экспертом.

**Comment by Milamesher** [comment]
Текущее выполнено, показано Захарову и Новиковой, всё устроило. Нужно добавить отчёт (форму подготовит экспертный отдел). ЭО так же может внести свои пожелания, правки и тп

**Comment by Milamesher** [comment]
ЭО хочет, чтобы за всё отвечали заведующие. От Захарова получена форма отчёта. Подготовлен материал к показу в пт, готов скрипт для БД.

**Comment by Milamesher** [comment]
Политика Mis\Order203 добавлена

**Comment by Milamesher** [comment]
Необходимо сделать возможность для врача выставлять Да/Нет, который потом утвердит заведующий (инф. от Захарова)

**Comment by Milamesher** [comment]
Надо добавить поля для взрослых/для детей (инф. от Новиковой)

**Comment by Milamesher** [comment]
Осталось учитывание критерия в самих экспертных картах. И баллы для врача.

**Comment by Milamesher** [comment]
Баллы врача. План: с тэга с критериями из СЛО - кнопка Создать черновик ЭК, которая создаст qecard в servicebean, проставит все поля, затем получит её id, создаст qe с card_id=id и с пометкой _черновик_, которую заполнит врач и которую потом сможет перезаполнить заведующий (и ему тоже показать, что это был черновик)

**Comment by Milamesher** [comment]
Получен от Жени список услуг и критериев для детей. Выполнен запрос:
update vocqualityestimationcrit set ischild=true  where kind_id=5

**Comment by Milamesher** [comment]
Добавлены стандартные политики для Order203

**Comment by Milamesher** [comment]
Выполнены 2 запроса от Жени.

**Comment by Milamesher** [comment]
сделано:
Активация стандартных политик для Order203
update vocqualityestimationcrit set medservicecodes=(select medservicecodes from vocqualityestimationcrit where id=1050) where id=1051;
update vocqualityestimationcrit set medservicecodes=null where id=1050;

**Comment by Milamesher** [comment]
Политика Order203 добавлена в роль клинико-экспертного отдела

**Comment by Milamesher** [comment]
Необходимо решить вопрос с экспертными картами из-под СЛС, а не СЛО.

**Comment by Milamesher** [comment]
Выполнен запрос
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1042 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1043 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1044 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1045 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1046 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1047 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1048 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';
INSERT INTO vocqualityestimationcrit_diagnosis(vocidc10_id, vqecrit_id) SELECT id, 1049 FROM vocidc10 WHERE code LIKE 'G50%' or code LIKE 'G51%' or code LIKE 'G52%' or code LIKE 'G54%' or code LIKE 'G56%' or code LIKE 'G57%' or code LIKE 'G58%' or code LIKE 'G59%';

**Comment by Milamesher** [comment]
2 недели прошло - закрываю задачу.

**Comment by Milamesher** [comment]
По заказу зав. эндокринологией: Оценки Да-Нет-Нет с комментарием (мб да с комментарием?) + отчёт для контролирующих организаций с сохранёнными комментариями.
