### ISSUE TITLE
Запретить направления пациентов на услуги, лежащих в стационаре (кроме платных)

### ISSUE THREAD

**Issue by vasek00786** [amokb/medos#68]
Все направления на диагностические услуги оформлять через лист назначений.

**Comment by Milamesher** [comment]
Кроме платного потока обслуживания: запретить регистратору добавлять направление персоне, если пациент лежит в стационаре. Т.е. для остальных потоков обслуживания такие назначения должны быть сделаны через лист назначений.

**Comment by Milamesher** [comment]
На данный момент можно делать любые направления, кроме ОМС. Женя уточнит у Захарова, какая политика в такой ситуации

**Comment by Milamesher** [comment]
Неактуальная задача.
