### ISSUE TITLE
Неонатологический случай смерти

### ISSUE THREAD

**Issue by vasek00786** [amokb/medos#74]
при создании новорожденных автоматом создавать "Неонатологический случай смерти". Должна быть возможность создания протокола КИЛИ по данному случаю с корректным формированием отчета (указывать, что случай смерти  - неонатологический, в журнале отображать данные матери.

**Comment by Milamesher** [comment]
Необходимо добавить в newbornform: если родился мёртвым, то обязательное поле для заполнения: акушерский диагноз (мкб и текст диагноза)

**Comment by Milamesher** [comment]
Необходимо переименовать неонатологический случай в мертворождение, а также разбить отчёт по КИЛИ на 2 этих случая. См. 13 и 14ю форму

**Comment by Milamesher** [comment]
Необходимо:
выгружать в протокол КИЛИ примечание; 
для акушерских случаев: выгружать причину смерти в протокол КИЛИ после соп. заболевания;
добавить новое поле История развития новорожденного в deathCase, в которое выгружать инфу (образец есть) - только в акушерском случае

**Comment by Milamesher** [comment]
Возобновляю работу над заданием в комментарии от 16 февраля.

**Comment by Milamesher** [comment]
Пока задачу не закрываю, вдруг ещё что сделать надо будет.

**Comment by Milamesher** [comment]
Пока никаких замечаний не получено, задачу закрываю.
