### ISSUE TITLE
Редактирование визита врачом

### ISSUE THREAD

**Issue by vasek00786** [amokb/medos#75]
возникают случаи дублирования заключений и диагнозов по визитам к врачам, ведущим амбулаторно-поликлинический прием.
Для устранения подобных ошибок прошу реализовать в МИС «МедОС» следующий функционал:
- при добавлении диагноза к визиту врача амбулаторно-поликлинической службы сделать следующее ограничение: количество диагнозов с приоритетом «Основной» должно быть не более одного;
- если по техническим причинам в визите есть более одного ОСНОВНОГО диагноза, разрешить врачу, осуществившему прием, удалить «лишние» диагнозы (то есть можно удалить ОСНОВНЫЕ диагнозы, пока их количество больше одного) в течении рабочего дня;
- другой вариант – сделать «кнопку»  - «удалить дублированные диагнозы», если по визиту есть дублированные диагнозы;

То же самое относится к заключению по визиту:
 - при добавлении заключения к визиту врача амбулаторно-поликлинической службы сделать следующее ограничение: количество заключений в визите не должно быть  более одного (ограничение не должно касаться диагностических служб – «рентгенологов», «узистов» и тд!);
-  если по техническим причинам в визите есть более одного заключения, разрешить врачу, осуществившему прием, в течении рабочего дня удалять «лишние» заключения (то есть можно удалять заключения, пока их количество больше одного);

**Comment by Milamesher** [comment]
Задача пока не начата, т.к. есть более приоритетная на данный момент - 203 приказ.

**Comment by Milamesher** [comment]
После обсуждения с Васей и Олегом:
- не больше одного основного любого (тут вопрос про основной клинический и основной выписной) в рамках СЛО и выписки
- не мб одинаковых диагнозов по приоритету и типу регистрации внутри СЛО, а также
в самой госпитализации не мб одинаковых д-в (опять приоритет и тип) - это уже где выписка, при этом в разных СЛО он может совпадать
- код мкб не должен повторяться в рамках СЛО и выписки (на форме Госпитализация), при этом в разных СЛО он может совпадать
- в приёмнике направительный может совпадать с при поступлении.

Задача отложена. Олег уточнит мед. вопросы по задаче
